/obj/effect/overmap/visitable/planet/Sif
/obj/effect/overmap/visitable/ship/landable/explorer_shuttle
/obj/effect/overmap/visitable/telecomm_sat
/obj/effect/shuttle_landmark/cynosure/arrivals_offsite
/obj/effect/shuttle_landmark/cynosure/arrivals_station
/obj/effect/shuttle_landmark/cynosure/escape_pod1/offsite
/obj/effect/shuttle_landmark/cynosure/escape_pod1/station
/obj/effect/shuttle_landmark/cynosure/escape_pod1/transit
/obj/effect/shuttle_landmark/cynosure/escape/offsite
/obj/effect/shuttle_landmark/cynosure/escape/station
/obj/effect/shuttle_landmark/cynosure/escape/transit
/obj/effect/shuttle_landmark/cynosure/large_escape_pod1/offsite
/obj/effect/shuttle_landmark/cynosure/large_escape_pod1/station
/obj/effect/shuttle_landmark/cynosure/large_escape_pod1/transit
/obj/effect/shuttle_landmark/cynosure/large_escape_pod2/offsite
/obj/effect/shuttle_landmark/cynosure/large_escape_pod2/station
/obj/effect/shuttle_landmark/cynosure/large_escape_pod2/transit
/obj/effect/shuttle_landmark/cynosure/pads/pad3
/obj/effect/shuttle_landmark/cynosure/pads/pad4
/obj/effect/shuttle_landmark/cynosure/pads/perimeter
/obj/effect/shuttle_landmark/cynosure/supply_offsite
/obj/effect/shuttle_landmark/cynosure/supply_station
/obj/effect/shuttle_landmark/cynosure/tcomms/dock
/obj/effect/shuttle_landmark/cynosure/tcomms/solars
/obj/effect/shuttle_landmark/cynosure/wilderness